#pragma once
#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>
#include "../HookMacros.h"


FUNC_DECL_ADDR(lua_newstate)
FUNC_DECL_ADDR(lua_close)
FUNC_DECL_ADDR(lua_newthread)
FUNC_DECL_ADDR(lua_atpanic)
//FUNC_DECL_ADDR(lua_gettop, USING_CODE)
FUNC_DECL_ADDR(lua_settop)
FUNC_DECL_ADDR(lua_pushvalue)
FUNC_DECL_ADDR(lua_remove)
FUNC_DECL_ADDR(lua_insert)
FUNC_DECL_ADDR(lua_replace)
FUNC_DECL_ADDR(lua_checkstack)
FUNC_DECL_ADDR(lua_xmove)
FUNC_DECL_ADDR(lua_isnumber)
FUNC_DECL_ADDR(lua_isstring)
FUNC_DECL_ADDR(lua_iscfunction)
//FUNC_DECL_ADDR(lua_isuserdata, USING_CODE)
FUNC_DECL_ADDR(lua_type)
//FUNC_DECL_ADDR(lua_typename, USING_CODE)
//FUNC_DECL_ADDR(lua_equal, NOT_FOUND)
FUNC_DECL_ADDR(lua_rawequal)
FUNC_DECL_ADDR(lua_lessthan)
FUNC_DECL_ADDR(lua_tonumber)
FUNC_DECL_ADDR(lua_tointeger)
FUNC_DECL_ADDR(lua_toboolean)
FUNC_DECL_ADDR(lua_tolstring)
FUNC_DECL_ADDR(lua_objlen)
FUNC_DECL_ADDR(lua_tocfunction)
FUNC_DECL_ADDR(lua_touserdata)
FUNC_DECL_ADDR(lua_tothread)
FUNC_DECL_ADDR(lua_topointer)
FUNC_DECL_ADDR(lua_pushnil)
FUNC_DECL_ADDR(lua_pushnumber)
FUNC_DECL_ADDR(lua_pushinteger)
FUNC_DECL_ADDR(lua_pushlstring)
FUNC_DECL_ADDR(lua_pushstring)
FUNC_DECL_ADDR(lua_pushvfstring)
FUNC_DECL_ADDR(lua_pushfstring)
FUNC_DECL_ADDR(lua_pushcclosure)
FUNC_DECL_ADDR(lua_pushboolean)
FUNC_DECL_ADDR(lua_pushlightuserdata)
FUNC_DECL_ADDR(lua_pushthread)
FUNC_DECL_ADDR(lua_gettable)
FUNC_DECL_ADDR(lua_getfield)
FUNC_DECL_ADDR(lua_rawget)
FUNC_DECL_ADDR(lua_rawgeti)
FUNC_DECL_ADDR(lua_createtable)
FUNC_DECL_ADDR(lua_newuserdata)
FUNC_DECL_ADDR(lua_getmetatable)
FUNC_DECL_ADDR(lua_getfenv)
FUNC_DECL_ADDR(lua_settable)
FUNC_DECL_ADDR(lua_setfield)
FUNC_DECL_ADDR(lua_rawset)
FUNC_DECL_ADDR(lua_rawseti)
FUNC_DECL_ADDR(lua_setmetatable)
FUNC_DECL_ADDR(lua_setfenv)
FUNC_DECL_ADDR(lua_call)
FUNC_DECL_ADDR(lua_pcall)
FUNC_DECL_ADDR(lua_cpcall)
FUNC_DECL_ADDR(lua_load)
FUNC_DECL_ADDR(lua_dump)
//FUNC_DECL_ADDR(lua_yield, USING_CODE)
FUNC_DECL_ADDR(lua_resume)
//FUNC_DECL_ADDR(lua_status, USING_CODE)
FUNC_DECL_ADDR(lua_gc)
FUNC_DECL_ADDR(lua_error)
FUNC_DECL_ADDR(lua_next)
FUNC_DECL_ADDR(lua_concat)
//FUNC_DECL_ADDR(lua_getallocf, NO_USE)
//FUNC_DECL_ADDR(lua_setallocf, NO_USE)
//FUNC_DECL_ADDR(lua_setlevel, NO_USE)
FUNC_DECL_ADDR(lua_getstack)
FUNC_DECL_ADDR(lua_getinfo)
FUNC_DECL_ADDR(lua_getlocal)
FUNC_DECL_ADDR(lua_setlocal)
FUNC_DECL_ADDR(lua_getupvalue)
FUNC_DECL_ADDR(lua_setupvalue)
FUNC_DECL_ADDR(lua_sethook)
//FUNC_DECL_ADDR(lua_gethook, USING_CODE)
//FUNC_DECL_ADDR(lua_gethookmask, USING_CODE)
//FUNC_DECL_ADDR(lua_gethookcount, USING_CODE)
FUNC_DECL_ADDR(luaI_openlib)
//FUNC_DECL_ADDR(luaL_register, USING_CODE)
FUNC_DECL_ADDR(luaL_getmetafield)
FUNC_DECL_ADDR(luaL_callmeta)
FUNC_DECL_ADDR(luaL_typerror)
FUNC_DECL_ADDR(luaL_argerror)
FUNC_DECL_ADDR(luaL_checklstring)
FUNC_DECL_ADDR(luaL_optlstring)
FUNC_DECL_ADDR(luaL_checknumber)
//FUNC_DECL_ADDR(luaL_optnumber, USING_CODE)
FUNC_DECL_ADDR(luaL_checkinteger)
FUNC_DECL_ADDR(luaL_optinteger)
FUNC_DECL_ADDR(luaL_checkstack)
FUNC_DECL_ADDR(luaL_checktype)
FUNC_DECL_ADDR(luaL_checkany)
FUNC_DECL_ADDR(luaL_newmetatable)
FUNC_DECL_ADDR(luaL_checkudata)
FUNC_DECL_ADDR(luaL_where)
FUNC_DECL_ADDR(luaL_error)
FUNC_DECL_ADDR(luaL_checkoption)
//FUNC_DECL_ADDR(luaL_ref, USING_CODE)
//FUNC_DECL_ADDR(luaL_unref, USING_CODE)
FUNC_DECL_ADDR(luaL_loadfile)
FUNC_DECL_ADDR(luaL_loadbuffer)
//FUNC_DECL_ADDR(luaL_loadstring, USING_CODE)
FUNC_DECL_ADDR(luaL_newstate)
FUNC_DECL_ADDR(luaL_gsub)
FUNC_DECL_ADDR(luaL_findtable)
//FUNC_DECL_ADDR(luaL_buffinit, USING_CODE)
FUNC_DECL_ADDR(luaL_prepbuffer)
FUNC_DECL_ADDR(luaL_addlstring)
//FUNC_DECL_ADDR(luaL_addstring, USING_CODE)
FUNC_DECL_ADDR(luaL_addvalue)
FUNC_DECL_ADDR(luaL_pushresult)
FUNC_DECL_ADDR(luaopen_base)
FUNC_DECL_ADDR(luaopen_table)
FUNC_DECL_ADDR(luaopen_io)
FUNC_DECL_ADDR(luaopen_os)
FUNC_DECL_ADDR(luaopen_string)
FUNC_DECL_ADDR(luaopen_math)
FUNC_DECL_ADDR(luaopen_debug)
FUNC_DECL_ADDR(luaopen_package)
FUNC_DECL_ADDR(luaL_openlibs)